# Generated by Django 5.0 on 2024-03-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='APPOINTMENT_TYPE',
            new_name='appointment_type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime'),
        ),
    ]
